### ISSUE TITLE
allow network identifier to be specified in connector parameters

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamConnectors#6]
For a pre-installed OpenStack cloud at IPHC, it is necessary to specify the network identifier associated with the public/private networks.  The command with the nova interface is:

```
$ nova boot … --nic net-id=e9bb6250-6d0c-48e3-8788-900789258fd7 ID
```

Should public/private network IDs be added as parameters for the cloud connector?  Or is there another way to support this functionality?  (Requiring a specific configuration of the IPHC cloud for SlipStream is not a desired solution.)

**Comment by Pansanel** [comment]
@schaubl : we can see in the following script https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/scripts/openstack-run-instances that private and public network are supported. If it is true, should we use net-id or name?

**Comment by schaubl** [comment]
@Pansanel : yes, you're right, this feature was implemented by @loomis since my last comment on this issue.
Currently the mapping is not defined in the user profile but in the connector configuration. So the mapping is defined per-cloud instead of per-user.
You should use the network **name** with `openstack-run-instances`.

**Comment by Pansanel** [comment]
Great news! Thank you :)
